### ISSUE TITLE
advance new file plugin can not work well

### ISSUE THREAD

**Issue by llleonzhao** [dempfi/neka-sublime#1]
Hi  I like neka theme very much! but advance new file plugin can not work well
![screen shot 2015-11-16 at 09 29 42](https://cloud.githubusercontent.com/assets/4151445/11172575/940f6ee0-8c44-11e5-872a-639f9221a01b.png)

**Comment by dempfi** [comment]
Thx mate. I'll test it. And fix it as soon as possible.

**Comment by dempfi** [comment]
@leon1314 this isn't bug in neka. take a look at the simple solution here https://github.com/equinusocio/material-theme/issues/67
