### ISSUE TITLE
my tabs are not how they should be

### ISSUE THREAD

**Issue by toctavian** [dempfi/neka-sublime#2]
![screenshot from 2015-12-07 14 21 57](https://cloud.githubusercontent.com/assets/15837218/11629158/6ac4fdba-9cee-11e5-9ded-e65762f8cd1e.png)

**Comment by dempfi** [comment]
Hi @toctavian. Can you share steps to reproduce this problem?

**Comment by dempfi** [comment]
@toctavian Feel free to reopen if it will be necessary.
