### ISSUE TITLE
Color scheme for porting to other apps

### ISSUE THREAD

**Issue by PatTheMav** [dempfi/neka-sublime#3]
Hey @dempfi - love the theme, stumbled upon it today and started using it instantly.

I just wish I could adapt my terminal and Xcode to the same theme. So is there a chance that you could release a scheme overview along the lines of the base16 set of colors? This would help in just "adapting" the existing base16 themes I got with the new colors.

Also one minor (and purely aesthetic request): I would love to see the tab indicator animation from the Material theme adapted here.

**Comment by dempfi** [comment]
hey @PatTheMav. Here is color definition from vim version of colorscheme. Try out them.

```
let s:palette.gui.background = "#080D12"
let s:palette.gui.foreground = "#DAE5F2"
let s:palette.gui.selection  = "#303840"
let s:palette.gui.line       = "#0F171F"
let s:palette.gui.comment    = "#525C66"
let s:palette.gui.red        = "#D7503C"
let s:palette.gui.orange     = "#FFAA33"
let s:palette.gui.yellow     = "#E7C547"
let s:palette.gui.green      = "#B9CA4A"
let s:palette.gui.aqua       = "#3DB4CC"
let s:palette.gui.blue       = "#2B9FD9"
let s:palette.gui.purple     = "#C397D8"
let s:palette.gui.delbg      = "#cc6666"
let s:palette.gui.darkblue   = "#00005f"
let s:palette.gui.darkcyan   = "#005f5f"
let s:palette.gui.darkred    = "#5f0000"
let s:palette.gui.darkpurple = "#5f005f"
```
