### ISSUE TITLE
Status Bar size option

### ISSUE THREAD

**Issue by sarvex** [dempfi/neka-sublime#4]
The Status Bar is too big for non-retina displays. There should be option to choose a smaller statusbar
   `"neka_theme_small_statusbar": true,`

**Comment by dempfi** [comment]
Hey @sarvex. Can you please share some screenshots?

**Comment by sarvex** [comment]
Narrow status bar (grab from Material Theme)
![Narrow status bar in Material Theme](https://cloud.githubusercontent.com/assets/1885938/13170677/d36ddfda-d713-11e5-8ea4-8cb600b5f99d.png)

Current status bar in Neka
![Current Status bar in Neka Theme](https://cloud.githubusercontent.com/assets/1885938/13170678/d372d3a0-d713-11e5-8f83-2912676670cd.png)

**Comment by dempfi** [comment]
@sarvex I added support for `"neka_theme_small_statusbar": "true"`.
