### ISSUE TITLE
ctrl+shift+g layout issue

### ISSUE THREAD

**Issue by atsea** [dempfi/neka-sublime#5]
I can't find what this is keymapped to but the text field is partially hidden when you hit ctrl+shift+g keys on Win 8.1 ST3 3083
![untitled-1](https://cloud.githubusercontent.com/assets/840437/13147856/ac34bb32-d628-11e5-98cf-807625651219.png)

**Comment by dempfi** [comment]
@atsea take a look on this issue https://github.com/dempfi/Neka-Theme/issues/1
